config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted,
  #                                      simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here,
  #                                      as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'sample#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    resources :suggests,   only: [:index]
    resources :products,   only: [:show]
    resources :categories, only: [:show]

    namespace :api do
      resources :suggests, only: [:index]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/potepan.rb
module Potepan
  def self.table_name_prefix
    "potepan_"
  end
end

app/models/potepan/product_decorator.rb
module Potepan::ProductDecorator
  def related_products
    Spree::Product.includes(master: [:images, :default_price]).
      joins(:classifications).
      merge(Spree::Classification.where(taxon_id: taxons.ids)).
      where.not(id: id).
      distinct.
      sample(NUM_OF_RELATED_PRODUCTS)
  end

  Spree::Product.prepend self
end

app/models/potepan/suggest.rb
class Potepan::Suggest < ActiveRecord::Base
  scope :items_start_with_keyword, ->(keyword) { where("keyword LIKE ?", "#{keyword}%") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/api/suggests_controller.rb
class Potepan::Api::SuggestsController < ApplicationController
  include ActionController::HttpAuthentication::Token::ControllerMethods
  before_action :authenticate

  def index
    if params[:keyword].nil?
      render_bad_request
      return
    end

    render json: suggest_list.pluck(:keyword)
  end

  private

  def suggest_list
    if params[:max_num].to_i.positive?
      output_count = [params[:max_num].to_i, SUGGEST_MAX_NUM_LIMIT].min
    else
      output_count = SUGGEST_MAX_NUM_LIMIT
    end
    Potepan::Suggest.items_start_with_keyword(params[:keyword]).limit(output_count)
  end

  def authenticate
    authenticate_token || render_unauthorized
  end

  def authenticate_token
    authenticate_with_http_token do |token, options|
      token == Rails.application.credentials.potepan_my_suggest[:api_key]
    end
  end

  def render_unauthorized
    render json: { error: { message: "unauthorized" } }, status: :unauthorized
  end

  def render_bad_request
    render json: { error: { message: "keyword can't be nil." } }, status: :bad_request
  end
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  def show
    @category = Spree::Taxon.find(params[:id])
    @products = @category.products.includes(master: [:images, :default_price])
    @major_categories = Spree::Taxonomy.all.includes(:root)
    @minor_categories = []
    @major_categories.each do |major_category|
      @minor_categories[major_category.id] = major_category.root.leaves.includes(:products)
    end
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  def show
    @product = Spree::Product.find(params[:id])
    @taxon = @product.taxons.joins(:taxonomy).merge(Spree::Taxonomy.where(name: "Categories")).first
    @taxon ||= @product.taxons.first
    @related_products = @product.related_products
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/controllers/potepan/suggests_controller.rb
require "httpclient"
class Potepan::SuggestsController < ApplicationController
  def index
    if params[:keyword].blank?
      logging_error("'keyword' is blank.")
      render status: 400, json: []
      return
    end

    response = Potepan::Suggests.client.get(
      Potepan::Suggests.url,
      Potepan::Suggests.query(keyword: params[:keyword]),
      Potepan::Suggests.header
    )
    if response.status != 200
      logging_error("Suggest request failed. ErrorCode: #{response.status}")
      render status: response.status, json: []
      return
    end

    suggests = JSON.parse(response.body)
    render json: suggests
  end

  private

  def logging_error(message)
    logger.error "Error!"
    logger.error "  message: #{message}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title: "")
    if page_title.blank?
      STORE_NAME
    else
      "#{page_title} - #{STORE_NAME}"
    end
  end
end

app/views/layouts/_footer.html.erb
<div id="footer" class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016-<%= Time.current.year %> Copyright Potepan Store .</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_light_section.html.erb
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= title %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li><%= link_to "Home", potepan_index_path %></li>
          <% if is_added_shop_link %>
            <li><%= link_to "shop", "#" %></li>
          <% end %>
          <li class="active page-title"><%= title %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_login_modal.html.erb
<div class="modal fade" id="login" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">log in</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="login-email">Enter Email</label>
            <input type="email" class="form-control" id="login-email">
          </div>
          <div class="form-group">
            <label for="login-password">Password</label>
            <input type="password" class="form-control" id="login-password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
          <button type="submit" class="btn btn-primary btn-block">log in</button>
          <button type="button" class="btn btn-link btn-block">Forgot Password?</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-main navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("img/logo.png"), potepan_index_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", potepan_index_path %></li>
        <li class="dropdown megaDropMenu active">
          <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/_partners_logo.html.erb
<div class="slide">
  <div class="partnersLogo clearfix">
    <%= image_tag(image, :alt => "partner-img") %>
  </div>
</div>

app/views/layouts/_partners_logo_slider.html.erb
<section class="lightSection clearfix">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="owl-carousel partnersLogoSlider">
          <%= render "layouts/partners_logo", image: "img/home/partners/partner-01.png" %>
          <%= render "layouts/partners_logo", image: "img/home/partners/partner-02.png" %>
          <%= render "layouts/partners_logo", image: "img/home/partners/partner-03.png" %>
          <%= render "layouts/partners_logo", image: "img/home/partners/partner-04.png" %>
          <%= render "layouts/partners_logo", image: "img/home/partners/partner-05.png" %>
          <%= render "layouts/partners_logo", image: "img/home/partners/partner-01.png" %>
          <%= render "layouts/partners_logo", image: "img/home/partners/partner-02.png" %>
          <%= render "layouts/partners_logo", image: "img/home/partners/partner-03.png" %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_shim.html.erb
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/_signup_modal.html.erb
<div class="modal fade" id="signup" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">Create an account</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="signup-email">Enter Email</label>
            <input type="email" class="form-control" id="signup-email">
          </div>
          <div class="form-group">
            <label for="signup-password">Password</label>
            <input type="password" class="form-control" id="signup-password">
          </div>
          <div class="form-group">
            <label for="signup-password-confirmation">Confirm Password</label>
            <input type="password" class="form-control" id="signup-password-confirmation">
          </div>
          <button type="submit" class="btn btn-primary btn-block">Sign up</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_topbar.html.erb
<div class="topBar">
  <div class="container">
    <div class="row">
      <div class="col-md-6 hidden-sm hidden-xs">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
      <div class="col-md-6 col-xs-12">
        <ul class="list-inline pull-right">
          <li class="dropdown searchBox">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <form id="form01" action="product-grid-left-sidebar.html" method="post">
                <li>
                  <span class="input-group">
                    <input type="text" name="searchWord" class="form-control" placeholder="Search…" aria-describedby="basic-addon2">
                    <span onclick="FormSubmit();" class="input-group-addon addPointer" id="basic-addon2">検索</span>
                  </span>
                </li>
              </form>
            </ul>
          </li>
          <li class="dropdown">
            <a href="cart-page.html" class="dropdown-toggle" data-toggle="dropdown disabled"><i class="fa fa-shopping-cart"></i></a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(page_title: yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <!-- HEADER -->
    <div class="header clearfix">
      <%= render "layouts/topbar" %>
      <%= render "layouts/navbar" %>
    </div>
    <%= yield %>
    <!-- LOGIN MODAL -->
    <%= render "layouts/login_modal" %>
    <!-- SIGN UP MODAL -->
    <%= render "layouts/signup_modal" %>
    <%= render "layouts/footer" %>
    <ul class="ui-autocomplete ui-front ui-menu ui-widget ui-widget-content" id="ui-id-1" tabindex="0" style="display: none;">
    </ul>
    <%= debug(params) if Rails.env.development? %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/potepan/categories/_category_sidebar.html.erb
<div class="panel panel-default panel-category">
  <div class="panel-heading">商品カテゴリー</div>
  <div class="panel-body">
    <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
      <ul class="nav navbar-nav side-nav">
        <% major_categories.each do |major_category| %>
          <li>
            <a href="javascript:;" data-toggle="collapse" data-target="#taxonomy-<%= major_category.id %>"><%= major_category.name %><i class="fa fa-plus"></i></a>
            <ul id="taxonomy-<%= major_category.id %>" class="collapse collapseItem">
              <% minor_categories[major_category.id].each do |minor_category| %>
                <% count = minor_category.products.to_a.count %>
                <% if count > 0 %>
                  <li>
                    <%= link_to potepan_category_path(minor_category.id) do %>
                      <i class="fa fa-caret-right" aria-hidden="true"></i><%= minor_category.name %> <span>(<%= count %>)</span>
                    <% end %>
                  </li>
                <% end %>
              <% end %>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/potepan/categories/_color_sidebar.html.erb
<div class="panel panel-default filterNormal panel-color">
  <div class="panel-heading">色から探す</div>
  <div class="panel-body">
    <ul class="list-unstyled">
      <li><a href="#">ブラック<span>(15)</span></a></li>
      <li><a href="#">ホワイト<span>(10)</span></a></li>
      <li><a href="#">レッド<span>(7)</span></a></li>
      <li><a href="#">ブルー<span>(12)</span></a></li>
      <li><a href="#">オレンジ<span>(12)</span></a></li>
    </ul>
  </div>
</div>

app/views/potepan/categories/_filter_area.html.erb
<div class="row filterArea">
  <div class="col-xs-6">
    <select name="guiest_id1" id="guiest_id1" class="select-drop">
      <option value="0">並び替え</option>
      <option value="1">人気順</option>
      <option value="2">安い順</option>
      <option value="3">新着順</option>
      <option value="3">高い順</option>
    </select>
  </div>
  <div class="col-xs-6">
    <div class="btn-group pull-right" role="group">
      <button type="button" class="btn btn-default active" onclick="window.location.href='product_grid_left_sidebar.html'"><i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
      <button type="button" class="btn btn-default" onclick="window.location.href='product_list_left_sidebar.html'"><i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
    </div>
  </div>
</div>

app/views/potepan/categories/_product.html.erb
<div class="col-sm-4 col-xs-12">
  <div class="productBox">
    <%= link_to potepan_product_path(product.id), class: "product-#{product.id}" do %>
      <div class="productImage clearfix">
        <% image = product.images.first %>
        <%= image_tag(image.attachment(:small), alt: image.alt) if image.present? %>
      </div>
      <div class="productCaption clearfix">
        <h5><%= product.name %></h5>
        <h3><%= product.display_price %></h3>
      </div>
    <% end %>
  </div>
</div>

app/views/potepan/categories/_size_sidebar.html.erb
<div class="panel panel-default filterNormal panel-size">
  <div class="panel-heading">サイズから探す</div>
  <div class="panel-body">
    <ul class="list-unstyled clearfix">
      <li><a href="#">S<span>(15)</span></a></li>
      <li><a href="#">M<span>(10)</span></a></li>
      <li><a href="#">L<span>(7)</span></a></li>
      <li><a href="#">XL<span>(12)</span></a></li>
    </ul>
  </div>
</div>

app/views/potepan/categories/show.html.erb
<% provide(:title, @category.name) %>
<!-- LIGHT SECTION -->
<%= render "layouts/light_section", title: @category.name, is_added_shop_link: true %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-4 col-xs-12 sideBar">
        <%= render "category_sidebar", major_categories: @major_categories, minor_categories: @minor_categories %>
        <%= render "color_sidebar" %>
        <%= render "size_sidebar" %>
      </div>
      <div class="col-md-9 col-sm-8 col-xs-12">
        <%= render "filter_area" %>
        <div class="row productsArea">
          <%= render partial: "product", collection: @products %>
        </div>
      </div>
    </div>
  </div>
</section>
<%= render "layouts/partners_logo_slider" %>

app/views/potepan/products/_order_field.html.erb
<span class="quick-drop">
  <select name="guiest_id3" id="guiest_id3" class="select-drop">
    <option value="0">S</option>
    <option value="1">M</option>
    <option value="2">L</option>
    <option value="3">XL</option>
  </select>
</span>
<span class="quick-drop resizeWidth">
  <select name="guiest_id4" id="guiest_id4" class="select-drop">
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
  </select>
</span>
<div class="btn-area">
  <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる<i class="fa fa-angle-right" aria-hidden="true"></i></a>
</div>

app/views/potepan/products/_product.html.erb
<div class="col-md-3 col-sm-6 col-xs-12">
  <div class="productBox">
    <%= link_to potepan_product_path(product.id), class: "product-#{product.id}" do %>
      <div class="productImage clearfix">
        <% image = product.images.first %>
        <%= image_tag(image.attachment(:small), alt: image.alt) if image.present? %>
      </div>
      <div class="productCaption clearfix">
        <h5><%= product.name %></h5>
        <h3><%= product.display_price %></h3>
      </div>
    <% end %>
  </div>
</div>

app/views/potepan/products/_product_image.html.erb
<div class="media-left productSlider">
  <div id="carousel" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <% product.images.each_with_index do |image, index| %>
        <div class="item <%= "active" if index.zero? %>" data-thumb="<%= index %>">
          <%= image_tag image.attachment(:large), alt: image.alt %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="clearfix">
    <div id="thumbcarousel" class="carousel slide" data-interval="false">
      <div class="carousel-inner">
        <% product.images.each_with_index do |image, index| %>
          <div data-target="#carousel" data-slide-to="<%= index %>" class="thumb">
            <%= image_tag image.attachment(:small), alt: image.alt %>
          </div>
        <% end %>
      </div>
      <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
      </a>
      <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
      </a>
    </div>
  </div>
</div>

app/views/potepan/products/_product_summary.html.erb
<h2><%= product.name %></h2>
<h3><%= product.display_price %></h3>
<p><%= product.description %></p>

app/views/potepan/products/_related_products.html.erb
<div class="row productsContent">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>関連商品</h4>
    </div>
  </div>
  <%= render partial: "product", collection: related_products %>
</div>

app/views/potepan/products/show.html.erb
<% provide(:title, @product.name) %>
<!-- LIGHT SECTION -->
<%= render "layouts/light_section", title: @product.name, is_added_shop_link: false %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <div class="row singleProduct">
      <div class="col-xs-12">
        <div class="media">
          <%= render "product_image", product: @product %>
          <div class="media-body">
            <ul class="list-inline">
              <li>
                <% if @taxon.present? %>
                  <%= link_to potepan_category_path(@taxon.id) do %>
                    <i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る
                  <% end %>
                <% end %>
              </li>
            </ul>
            <%= render "product_summary", product: @product %>
            <%= render "order_field" %>
          </div>
        </div>
      </div>
    </div>
    <%= render "related_products", related_products: @related_products if @related_products.present? %>
  </div>
</section>